### PR TITLE
Drop support for Node 8

### PR DESCRIPTION
**Pull request by scalvert**

### CODE REVIEW

**Comment by scalvert** [comment]
@rwjblue there seems to be an issue with `ember-test-waiters`' version in the ember-try scenarios, where it's not able to find the module. I don't believe the version it's trying to use is the broken version we fixed a few weeks ago. Also, looking at the vendor file I can see the module name is correct (the error is complaining it can't find `ember-test-waiters`). 

I'll try to dig into it to see what the issue is.

**Comment by rwjblue** [comment]
@scalvert - What version of ember-test-waiters is in use?

**Comment by scalvert** [comment]
```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "ember-test-waiters"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ember-test-waiters@2.1.2"
info Has been hoisted to "ember-test-waiters"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "19.31MB"
info Disk size with unique dependencies: "21.99MB"
info Disk size with transitive dependencies: "136.07MB"
info Number of shared dependencies: 225
=> Found "@ember/test-helpers#ember-test-waiters@1.2.0"
info This module exists because "ember-qunit#@ember#test-helpers" depends on it.
info Disk size without dependencies: "204KB"
info Disk size with unique dependencies: "1.77MB"
info Disk size with transitive dependencies: "115.09MB"
info Number of shared dependencies: 208
✨  Done in 1.57s.
```

The project depends directly on 2.1.2, but `@ember/test-helpers` depends on 1.2.0.

Since we dedupe via [`forceHighlander`](https://github.com/emberjs/ember-test-waiters/blob/v2.1.2/index.js#L11), we ultimately end up with 2.1.2. I have confirmed this by looking at what's built in `dist/assets/vendor.js`. I have also confirmed that the correct module name is exported.

**Comment by scalvert** [comment]
Fixed the issue with incorrect module exports in `ember-test-waiters` https://github.com/emberjs/ember-test-waiters/pull/165

**Pull request merged**
